name: Flutter CI - Android & iOS Build

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  android-build:
    name: Android Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Flutter SDK
        uses: actions/cache@v3
        with:
          path: ${{ runner.tool_cache }}/flutter
          key: "flutter-${{ runner.os }}-${{ hashFiles('**/pubspec.yaml') }}"
          restore-keys: |
            flutter-${{ runner.os }}-

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.24.4

      - name: Cache pub dependencies
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: "flutter-pub-${{ runner.os }}-${{ hashFiles('**/pubspec.yaml') }}"
          restore-keys: |
            flutter-pub-${{ runner.os }}-

      - name: Install dependencies
        run: flutter pub get

      - name: Build Android release APK
        run: flutter build apk --release

      - name: Build Android App Bundle
        run: flutter build appbundle --release

  ios-build:
    name: iOS Build
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Flutter SDK
        uses: actions/cache@v3
        with:
          path: ${{ runner.tool_cache }}/flutter
          key: "flutter-${{ runner.os }}-${{ hashFiles('**/pubspec.yaml') }}"
          restore-keys: |
            flutter-${{ runner.os }}-

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.24.4

      - name: Cache pub dependencies
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: "flutter-pub-${{ runner.os }}-${{ hashFiles('**/pubspec.yaml') }}"
          restore-keys: |
            flutter-pub-${{ runner.os }}-

      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS release
        run: flutter build ios --release --no-codesign
